export const SET_USERS = "SET_USERS";
export const GET_ERRORS = "GET_ERRORS";
export const CLEAR_ERRORS = "CLEAR_ERRORS";
export const LOADING_DATA = "LOADING_DATA";
export const GET_PROJECT_DATA = "GET_PROJECT_DATA";
export const GET_PROJECTDETAIL_DATA = "GET_PROJECTDETAIL_DATA";
export const GET_ROMMDETAIL_DATA = "GET_ROMMDETAIL_DATA";
export const GET_HISTORY_DATA = "GET_HISTORY_DATA";
